import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import * as XLSX from 'xlsx';
import { saveAs } from 'file-saver';

/**
 * Export analytics data to PDF
 * @param {Object} data - Analytics data object
 * @param {string} period - Selected period
 * @param {Object} filters - Applied filters
 */
export const exportToPDF = async (data, period, filters) => {
  try {
    const pdf = new jsPDF('l', 'mm', 'a4'); // Landscape orientation
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    
    // Title
    pdf.setFontSize(20);
    pdf.setFont('helvetica', 'bold');
    pdf.text('RoadAssist BD - Analytics Report', pageWidth / 2, 20, { align: 'center' });
    
    // Period and filters info
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`Period: ${period}`, 20, 35);
    pdf.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth - 80, 35);
    
    if (filters.vehicleType) {
      pdf.text(`Vehicle Type: ${filters.vehicleType}`, 20, 45);
    }
    if (filters.problemType) {
      pdf.text(`Problem Type: ${filters.problemType}`, 20, 55);
    }
    
    let yPosition = 70;
    
    // Overview section
    pdf.setFontSize(16);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Overview Metrics', 20, yPosition);
    yPosition += 15;
    
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'normal');
    
    if (data.requests?.overview) {
      pdf.text(`Total Requests: ${data.requests.overview.totalRequests}`, 20, yPosition);
      yPosition += 10;
      pdf.text(`Completed Requests: ${data.requests.overview.completedRequests}`, 20, yPosition);
      yPosition += 10;
      pdf.text(`Requests Growth: ${data.requests.overview.requestsGrowth}%`, 20, yPosition);
      yPosition += 10;
    }
    
    if (data.revenue?.overview) {
      pdf.text(`Total Revenue: BDT ${data.revenue.overview.totalRevenue.toLocaleString()}`, 20, yPosition);
      yPosition += 10;
      pdf.text(`Revenue Growth: ${data.revenue.overview.revenueGrowth}%`, 20, yPosition);
      yPosition += 10;
    }
    
    if (data.performance?.overview) {
      pdf.text(`Average Response Time: ${data.performance.overview.avgResponseTime} min`, 20, yPosition);
      yPosition += 10;
      pdf.text(`Average Rating: ${data.performance.overview.avgRating}/5`, 20, yPosition);
      yPosition += 10;
    }
    
    yPosition += 20;
    
    // Vehicle Type Distribution
    if (data.requests?.vehicleTypeDistribution?.length > 0) {
      pdf.setFontSize(16);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Vehicle Type Distribution', 20, yPosition);
      yPosition += 15;
      
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'normal');
      
      data.requests.vehicleTypeDistribution.forEach(item => {
        pdf.text(`${item._id}: ${item.count} requests`, 30, yPosition);
        yPosition += 10;
      });
      yPosition += 10;
    }
    
    // Problem Type Distribution
    if (data.requests?.problemTypeDistribution?.length > 0) {
      pdf.setFontSize(16);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Problem Type Distribution', 20, yPosition);
      yPosition += 15;
      
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'normal');
      
      data.requests.problemTypeDistribution.forEach(item => {
        pdf.text(`${item._id}: ${item.count} requests`, 30, yPosition);
        yPosition += 10;
      });
      yPosition += 10;
    }
    
    // Top Mechanics
    if (data.performance?.topMechanics?.length > 0) {
      pdf.setFontSize(16);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Top Performing Mechanics', 20, yPosition);
      yPosition += 15;
      
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'normal');
      
      data.performance.topMechanics.slice(0, 10).forEach((mechanic, index) => {
        pdf.text(`${index + 1}. ${mechanic.user.name}: ${mechanic.completedJobs} jobs, ${mechanic.avgRating?.toFixed(1)} rating`, 30, yPosition);
        yPosition += 10;
      });
    }
    
    // Footer
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'italic');
    pdf.text('Generated by RoadAssist BD Admin Panel', pageWidth / 2, pageHeight - 10, { align: 'center' });
    
    // Save the PDF
    const fileName = `analytics-report-${period}-${new Date().toISOString().split('T')[0]}.pdf`;
    pdf.save(fileName);
    
    return true;
  } catch (error) {
    console.error('Error generating PDF:', error);
    throw new Error('Failed to generate PDF report');
  }
};

/**
 * Export analytics data to Excel
 * @param {Object} data - Analytics data object
 * @param {string} period - Selected period
 * @param {Object} filters - Applied filters
 */
export const exportToExcel = (data, period, filters) => {
  try {
    const workbook = XLSX.utils.book_new();
    
    // Overview Sheet
    const overviewData = [];
    if (data.requests?.overview) {
      overviewData.push(
        ['Metric', 'Value'],
        ['Total Requests', data.requests.overview.totalRequests],
        ['Completed Requests', data.requests.overview.completedRequests],
        ['Requests Growth (%)', data.requests.overview.requestsGrowth],
        ['Completed Growth (%)', data.requests.overview.completedGrowth]
      );
    }
    
    if (data.revenue?.overview) {
      overviewData.push(
        ['Total Revenue (BDT)', data.revenue.overview.totalRevenue],
        ['Total Orders', data.revenue.overview.totalOrders],
        ['Average Order Value (BDT)', data.revenue.overview.avgOrderValue],
        ['Revenue Growth (%)', data.revenue.overview.revenueGrowth]
      );
    }
    
    if (data.performance?.overview) {
      overviewData.push(
        ['Average Response Time (min)', data.performance.overview.avgResponseTime],
        ['Average Rating', data.performance.overview.avgRating],
        ['Total Ratings', data.performance.overview.totalRatings],
        ['Rating Growth (%)', data.performance.overview.ratingGrowth]
      );
    }
    
    const overviewSheet = XLSX.utils.aoa_to_sheet(overviewData);
    XLSX.utils.book_append_sheet(workbook, overviewSheet, 'Overview');
    
    // Daily Requests Sheet
    if (data.requests?.dailyRequests?.length > 0) {
      const requestsData = [
        ['Date', 'Total Requests', 'Completed', 'Cancelled', 'Pending', 'In Progress', 'Total Revenue', 'Avg Cost']
      ];
      
      data.requests.dailyRequests.forEach(item => {
        requestsData.push([
          item._id.date,
          item.total,
          item.completed,
          item.cancelled,
          item.pending,
          item.inProgress,
          item.totalRevenue || 0,
          item.avgCost || 0
        ]);
      });
      
      const requestsSheet = XLSX.utils.aoa_to_sheet(requestsData);
      XLSX.utils.book_append_sheet(workbook, requestsSheet, 'Daily Requests');
    }
    
    // Daily Revenue Sheet
    if (data.revenue?.dailyRevenue?.length > 0) {
      const revenueData = [
        ['Date', 'Revenue (BDT)', 'Orders Count', 'Avg Order Value (BDT)']
      ];
      
      data.revenue.dailyRevenue.forEach(item => {
        revenueData.push([
          item._id.date,
          item.revenue,
          item.count,
          item.avgOrderValue
        ]);
      });
      
      const revenueSheet = XLSX.utils.aoa_to_sheet(revenueData);
      XLSX.utils.book_append_sheet(workbook, revenueSheet, 'Daily Revenue');
    }
    
    // Vehicle Type Distribution Sheet
    if (data.requests?.vehicleTypeDistribution?.length > 0) {
      const vehicleData = [
        ['Vehicle Type', 'Total Requests', 'Completed Requests', 'Revenue (BDT)']
      ];
      
      data.requests.vehicleTypeDistribution.forEach(item => {
        vehicleData.push([
          item._id,
          item.count,
          item.completed,
          item.revenue || 0
        ]);
      });
      
      const vehicleSheet = XLSX.utils.aoa_to_sheet(vehicleData);
      XLSX.utils.book_append_sheet(workbook, vehicleSheet, 'Vehicle Types');
    }
    
    // Problem Type Distribution Sheet
    if (data.requests?.problemTypeDistribution?.length > 0) {
      const problemData = [
        ['Problem Type', 'Total Requests', 'Completed Requests', 'Avg Cost (BDT)']
      ];
      
      data.requests.problemTypeDistribution.forEach(item => {
        problemData.push([
          item._id,
          item.count,
          item.completed,
          item.avgCost || 0
        ]);
      });
      
      const problemSheet = XLSX.utils.aoa_to_sheet(problemData);
      XLSX.utils.book_append_sheet(workbook, problemSheet, 'Problem Types');
    }
    
    // Top Mechanics Sheet
    if (data.performance?.topMechanics?.length > 0) {
      const mechanicsData = [
        ['Rank', 'Mechanic Name', 'Completed Jobs', 'Average Rating', 'Total Earnings (BDT)', 'Avg Response Time (min)']
      ];
      
      data.performance.topMechanics.forEach((mechanic, index) => {
        mechanicsData.push([
          index + 1,
          mechanic.user.name,
          mechanic.completedJobs,
          mechanic.avgRating?.toFixed(1) || 0,
          mechanic.totalEarnings,
          mechanic.avgResponseTime?.toFixed(1) || 0
        ]);
      });
      
      const mechanicsSheet = XLSX.utils.aoa_to_sheet(mechanicsData);
      XLSX.utils.book_append_sheet(workbook, mechanicsSheet, 'Top Mechanics');
    }
    
    // Save the Excel file
    const fileName = `analytics-report-${period}-${new Date().toISOString().split('T')[0]}.xlsx`;
    XLSX.writeFile(workbook, fileName);
    
    return true;
  } catch (error) {
    console.error('Error generating Excel:', error);
    throw new Error('Failed to generate Excel report');
  }
};

/**
 * Export chart as image
 * @param {string} chartId - ID of the chart element
 * @param {string} fileName - Name for the exported file
 */
export const exportChartAsImage = async (chartId, fileName) => {
  try {
    const chartElement = document.getElementById(chartId);
    if (!chartElement) {
      throw new Error('Chart element not found');
    }
    
    const canvas = await html2canvas(chartElement, {
      backgroundColor: '#ffffff',
      scale: 2,
      useCORS: true
    });
    
    const link = document.createElement('a');
    link.download = `${fileName}.png`;
    link.href = canvas.toDataURL();
    link.click();
    
    return true;
  } catch (error) {
    console.error('Error exporting chart:', error);
    throw new Error('Failed to export chart as image');
  }
};
